# Generated by Django 5.0.6 on 2024-05-12 18:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Formato permitido: '+52 4431234567'. Diez digitos.", regex='^\\+?52?\\d{10,10}$')]),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
