# Generated by Django 5.0.6 on 2024-05-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0004_alter_cliente_telefono_alter_cliente_user_id_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
