# Generated by Django 5.0.6 on 2024-05-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0005_prestamo_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cantidad_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
