# Generated by Django 5.0.6 on 2024-05-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0006_alter_prestamo_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(max_length=5),
        ),
    ]
