# Generated by Django 5.0.6 on 2024-06-05 23:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0007_cliente_email_alter_cliente_cp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='cliente_id',
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=7)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('parcialidades', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)])),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('por_entregar', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiera.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos_encargados', to='financiera.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='financiera.pedidos')),
            ],
        ),
        migrations.DeleteModel(
            name='Abono',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
