# Generated by Django 5.0.6 on 2024-06-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0008_remove_prestamo_cliente_id_pedidos_articulos_abonos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='interes',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='parcialidades',
        ),
        migrations.AlterField(
            model_name='articulos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='calle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='cantidad_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True),
        ),
    ]
