# Generated by Django 5.0.6 on 2024-06-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0009_remove_pedidos_interes_remove_pedidos_parcialidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
